// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// StaffsColumns holds the columns for the "staffs" table.
	StaffsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "email", Type: field.TypeString, Size: 50},
		{Name: "role", Type: field.TypeInt32},
		{Name: "last_name", Type: field.TypeString, Size: 20},
		{Name: "first_name", Type: field.TypeString, Size: 20},
		{Name: "gender", Type: field.TypeInt32},
		{Name: "phone_number", Type: field.TypeString, Nullable: true, Size: 20},
		{Name: "description", Type: field.TypeString, Nullable: true, Size: 500},
		{Name: "user_id", Type: field.TypeUUID},
	}
	// StaffsTable holds the schema information for the "staffs" table.
	StaffsTable = &schema.Table{
		Name:       "staffs",
		Columns:    StaffsColumns,
		PrimaryKey: []*schema.Column{StaffsColumns[0]},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "user_type", Type: field.TypeInt32},
		{Name: "password_hash", Type: field.TypeString, Nullable: true, Size: 32},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		StaffsTable,
		UsersTable,
	}
)

func init() {
}
