// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"ent-sample/ent/predicate"
	"ent-sample/ent/staff"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// StaffUpdate is the builder for updating Staff entities.
type StaffUpdate struct {
	config
	hooks    []Hook
	mutation *StaffMutation
}

// Where appends a list predicates to the StaffUpdate builder.
func (su *StaffUpdate) Where(ps ...predicate.Staff) *StaffUpdate {
	su.mutation.Where(ps...)
	return su
}

// SetEmail sets the "email" field.
func (su *StaffUpdate) SetEmail(s string) *StaffUpdate {
	su.mutation.SetEmail(s)
	return su
}

// SetRole sets the "role" field.
func (su *StaffUpdate) SetRole(i int32) *StaffUpdate {
	su.mutation.ResetRole()
	su.mutation.SetRole(i)
	return su
}

// AddRole adds i to the "role" field.
func (su *StaffUpdate) AddRole(i int32) *StaffUpdate {
	su.mutation.AddRole(i)
	return su
}

// SetLastName sets the "lastName" field.
func (su *StaffUpdate) SetLastName(s string) *StaffUpdate {
	su.mutation.SetLastName(s)
	return su
}

// SetFirstName sets the "firstName" field.
func (su *StaffUpdate) SetFirstName(s string) *StaffUpdate {
	su.mutation.SetFirstName(s)
	return su
}

// SetGender sets the "gender" field.
func (su *StaffUpdate) SetGender(i int32) *StaffUpdate {
	su.mutation.ResetGender()
	su.mutation.SetGender(i)
	return su
}

// AddGender adds i to the "gender" field.
func (su *StaffUpdate) AddGender(i int32) *StaffUpdate {
	su.mutation.AddGender(i)
	return su
}

// SetPhoneNumber sets the "phoneNumber" field.
func (su *StaffUpdate) SetPhoneNumber(s string) *StaffUpdate {
	su.mutation.SetPhoneNumber(s)
	return su
}

// SetNillablePhoneNumber sets the "phoneNumber" field if the given value is not nil.
func (su *StaffUpdate) SetNillablePhoneNumber(s *string) *StaffUpdate {
	if s != nil {
		su.SetPhoneNumber(*s)
	}
	return su
}

// ClearPhoneNumber clears the value of the "phoneNumber" field.
func (su *StaffUpdate) ClearPhoneNumber() *StaffUpdate {
	su.mutation.ClearPhoneNumber()
	return su
}

// SetDescription sets the "description" field.
func (su *StaffUpdate) SetDescription(s string) *StaffUpdate {
	su.mutation.SetDescription(s)
	return su
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (su *StaffUpdate) SetNillableDescription(s *string) *StaffUpdate {
	if s != nil {
		su.SetDescription(*s)
	}
	return su
}

// ClearDescription clears the value of the "description" field.
func (su *StaffUpdate) ClearDescription() *StaffUpdate {
	su.mutation.ClearDescription()
	return su
}

// SetUserId sets the "userId" field.
func (su *StaffUpdate) SetUserId(u uuid.UUID) *StaffUpdate {
	su.mutation.SetUserId(u)
	return su
}

// Mutation returns the StaffMutation object of the builder.
func (su *StaffUpdate) Mutation() *StaffMutation {
	return su.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (su *StaffUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(su.hooks) == 0 {
		if err = su.check(); err != nil {
			return 0, err
		}
		affected, err = su.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*StaffMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = su.check(); err != nil {
				return 0, err
			}
			su.mutation = mutation
			affected, err = su.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(su.hooks) - 1; i >= 0; i-- {
			if su.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = su.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, su.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (su *StaffUpdate) SaveX(ctx context.Context) int {
	affected, err := su.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (su *StaffUpdate) Exec(ctx context.Context) error {
	_, err := su.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (su *StaffUpdate) ExecX(ctx context.Context) {
	if err := su.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (su *StaffUpdate) check() error {
	if v, ok := su.mutation.Email(); ok {
		if err := staff.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf("ent: validator failed for field \"email\": %w", err)}
		}
	}
	if v, ok := su.mutation.Role(); ok {
		if err := staff.RoleValidator(v); err != nil {
			return &ValidationError{Name: "role", err: fmt.Errorf("ent: validator failed for field \"role\": %w", err)}
		}
	}
	if v, ok := su.mutation.LastName(); ok {
		if err := staff.LastNameValidator(v); err != nil {
			return &ValidationError{Name: "lastName", err: fmt.Errorf("ent: validator failed for field \"lastName\": %w", err)}
		}
	}
	if v, ok := su.mutation.FirstName(); ok {
		if err := staff.FirstNameValidator(v); err != nil {
			return &ValidationError{Name: "firstName", err: fmt.Errorf("ent: validator failed for field \"firstName\": %w", err)}
		}
	}
	if v, ok := su.mutation.Gender(); ok {
		if err := staff.GenderValidator(v); err != nil {
			return &ValidationError{Name: "gender", err: fmt.Errorf("ent: validator failed for field \"gender\": %w", err)}
		}
	}
	if v, ok := su.mutation.PhoneNumber(); ok {
		if err := staff.PhoneNumberValidator(v); err != nil {
			return &ValidationError{Name: "phoneNumber", err: fmt.Errorf("ent: validator failed for field \"phoneNumber\": %w", err)}
		}
	}
	if v, ok := su.mutation.Description(); ok {
		if err := staff.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf("ent: validator failed for field \"description\": %w", err)}
		}
	}
	return nil
}

func (su *StaffUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   staff.Table,
			Columns: staff.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: staff.FieldID,
			},
		},
	}
	if ps := su.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := su.mutation.Email(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: staff.FieldEmail,
		})
	}
	if value, ok := su.mutation.Role(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt32,
			Value:  value,
			Column: staff.FieldRole,
		})
	}
	if value, ok := su.mutation.AddedRole(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt32,
			Value:  value,
			Column: staff.FieldRole,
		})
	}
	if value, ok := su.mutation.LastName(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: staff.FieldLastName,
		})
	}
	if value, ok := su.mutation.FirstName(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: staff.FieldFirstName,
		})
	}
	if value, ok := su.mutation.Gender(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt32,
			Value:  value,
			Column: staff.FieldGender,
		})
	}
	if value, ok := su.mutation.AddedGender(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt32,
			Value:  value,
			Column: staff.FieldGender,
		})
	}
	if value, ok := su.mutation.PhoneNumber(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: staff.FieldPhoneNumber,
		})
	}
	if su.mutation.PhoneNumberCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Column: staff.FieldPhoneNumber,
		})
	}
	if value, ok := su.mutation.Description(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: staff.FieldDescription,
		})
	}
	if su.mutation.DescriptionCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Column: staff.FieldDescription,
		})
	}
	if value, ok := su.mutation.UserId(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeUUID,
			Value:  value,
			Column: staff.FieldUserId,
		})
	}
	if n, err = sqlgraph.UpdateNodes(ctx, su.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{staff.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return 0, err
	}
	return n, nil
}

// StaffUpdateOne is the builder for updating a single Staff entity.
type StaffUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *StaffMutation
}

// SetEmail sets the "email" field.
func (suo *StaffUpdateOne) SetEmail(s string) *StaffUpdateOne {
	suo.mutation.SetEmail(s)
	return suo
}

// SetRole sets the "role" field.
func (suo *StaffUpdateOne) SetRole(i int32) *StaffUpdateOne {
	suo.mutation.ResetRole()
	suo.mutation.SetRole(i)
	return suo
}

// AddRole adds i to the "role" field.
func (suo *StaffUpdateOne) AddRole(i int32) *StaffUpdateOne {
	suo.mutation.AddRole(i)
	return suo
}

// SetLastName sets the "lastName" field.
func (suo *StaffUpdateOne) SetLastName(s string) *StaffUpdateOne {
	suo.mutation.SetLastName(s)
	return suo
}

// SetFirstName sets the "firstName" field.
func (suo *StaffUpdateOne) SetFirstName(s string) *StaffUpdateOne {
	suo.mutation.SetFirstName(s)
	return suo
}

// SetGender sets the "gender" field.
func (suo *StaffUpdateOne) SetGender(i int32) *StaffUpdateOne {
	suo.mutation.ResetGender()
	suo.mutation.SetGender(i)
	return suo
}

// AddGender adds i to the "gender" field.
func (suo *StaffUpdateOne) AddGender(i int32) *StaffUpdateOne {
	suo.mutation.AddGender(i)
	return suo
}

// SetPhoneNumber sets the "phoneNumber" field.
func (suo *StaffUpdateOne) SetPhoneNumber(s string) *StaffUpdateOne {
	suo.mutation.SetPhoneNumber(s)
	return suo
}

// SetNillablePhoneNumber sets the "phoneNumber" field if the given value is not nil.
func (suo *StaffUpdateOne) SetNillablePhoneNumber(s *string) *StaffUpdateOne {
	if s != nil {
		suo.SetPhoneNumber(*s)
	}
	return suo
}

// ClearPhoneNumber clears the value of the "phoneNumber" field.
func (suo *StaffUpdateOne) ClearPhoneNumber() *StaffUpdateOne {
	suo.mutation.ClearPhoneNumber()
	return suo
}

// SetDescription sets the "description" field.
func (suo *StaffUpdateOne) SetDescription(s string) *StaffUpdateOne {
	suo.mutation.SetDescription(s)
	return suo
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (suo *StaffUpdateOne) SetNillableDescription(s *string) *StaffUpdateOne {
	if s != nil {
		suo.SetDescription(*s)
	}
	return suo
}

// ClearDescription clears the value of the "description" field.
func (suo *StaffUpdateOne) ClearDescription() *StaffUpdateOne {
	suo.mutation.ClearDescription()
	return suo
}

// SetUserId sets the "userId" field.
func (suo *StaffUpdateOne) SetUserId(u uuid.UUID) *StaffUpdateOne {
	suo.mutation.SetUserId(u)
	return suo
}

// Mutation returns the StaffMutation object of the builder.
func (suo *StaffUpdateOne) Mutation() *StaffMutation {
	return suo.mutation
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (suo *StaffUpdateOne) Select(field string, fields ...string) *StaffUpdateOne {
	suo.fields = append([]string{field}, fields...)
	return suo
}

// Save executes the query and returns the updated Staff entity.
func (suo *StaffUpdateOne) Save(ctx context.Context) (*Staff, error) {
	var (
		err  error
		node *Staff
	)
	if len(suo.hooks) == 0 {
		if err = suo.check(); err != nil {
			return nil, err
		}
		node, err = suo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*StaffMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = suo.check(); err != nil {
				return nil, err
			}
			suo.mutation = mutation
			node, err = suo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(suo.hooks) - 1; i >= 0; i-- {
			if suo.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = suo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, suo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (suo *StaffUpdateOne) SaveX(ctx context.Context) *Staff {
	node, err := suo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (suo *StaffUpdateOne) Exec(ctx context.Context) error {
	_, err := suo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (suo *StaffUpdateOne) ExecX(ctx context.Context) {
	if err := suo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (suo *StaffUpdateOne) check() error {
	if v, ok := suo.mutation.Email(); ok {
		if err := staff.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf("ent: validator failed for field \"email\": %w", err)}
		}
	}
	if v, ok := suo.mutation.Role(); ok {
		if err := staff.RoleValidator(v); err != nil {
			return &ValidationError{Name: "role", err: fmt.Errorf("ent: validator failed for field \"role\": %w", err)}
		}
	}
	if v, ok := suo.mutation.LastName(); ok {
		if err := staff.LastNameValidator(v); err != nil {
			return &ValidationError{Name: "lastName", err: fmt.Errorf("ent: validator failed for field \"lastName\": %w", err)}
		}
	}
	if v, ok := suo.mutation.FirstName(); ok {
		if err := staff.FirstNameValidator(v); err != nil {
			return &ValidationError{Name: "firstName", err: fmt.Errorf("ent: validator failed for field \"firstName\": %w", err)}
		}
	}
	if v, ok := suo.mutation.Gender(); ok {
		if err := staff.GenderValidator(v); err != nil {
			return &ValidationError{Name: "gender", err: fmt.Errorf("ent: validator failed for field \"gender\": %w", err)}
		}
	}
	if v, ok := suo.mutation.PhoneNumber(); ok {
		if err := staff.PhoneNumberValidator(v); err != nil {
			return &ValidationError{Name: "phoneNumber", err: fmt.Errorf("ent: validator failed for field \"phoneNumber\": %w", err)}
		}
	}
	if v, ok := suo.mutation.Description(); ok {
		if err := staff.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf("ent: validator failed for field \"description\": %w", err)}
		}
	}
	return nil
}

func (suo *StaffUpdateOne) sqlSave(ctx context.Context) (_node *Staff, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   staff.Table,
			Columns: staff.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: staff.FieldID,
			},
		},
	}
	id, ok := suo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "ID", err: fmt.Errorf("missing Staff.ID for update")}
	}
	_spec.Node.ID.Value = id
	if fields := suo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, staff.FieldID)
		for _, f := range fields {
			if !staff.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != staff.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := suo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := suo.mutation.Email(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: staff.FieldEmail,
		})
	}
	if value, ok := suo.mutation.Role(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt32,
			Value:  value,
			Column: staff.FieldRole,
		})
	}
	if value, ok := suo.mutation.AddedRole(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt32,
			Value:  value,
			Column: staff.FieldRole,
		})
	}
	if value, ok := suo.mutation.LastName(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: staff.FieldLastName,
		})
	}
	if value, ok := suo.mutation.FirstName(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: staff.FieldFirstName,
		})
	}
	if value, ok := suo.mutation.Gender(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt32,
			Value:  value,
			Column: staff.FieldGender,
		})
	}
	if value, ok := suo.mutation.AddedGender(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt32,
			Value:  value,
			Column: staff.FieldGender,
		})
	}
	if value, ok := suo.mutation.PhoneNumber(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: staff.FieldPhoneNumber,
		})
	}
	if suo.mutation.PhoneNumberCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Column: staff.FieldPhoneNumber,
		})
	}
	if value, ok := suo.mutation.Description(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: staff.FieldDescription,
		})
	}
	if suo.mutation.DescriptionCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Column: staff.FieldDescription,
		})
	}
	if value, ok := suo.mutation.UserId(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeUUID,
			Value:  value,
			Column: staff.FieldUserId,
		})
	}
	_node = &Staff{config: suo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, suo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{staff.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	return _node, nil
}
