// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Staff is the predicate function for staff builders.
type Staff func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
